Remote blog
ole-vi/treehouses.github.io.old pull request #35
Opened 2019-01-27 13:38 UTC by empeje

To test:

```
docker-compose up -d
```

2019-01-28 09:50 UTC, lmmrssa approved these changes
Looks nice as always

2019-01-28 12:55 UTC, dogi requested changes
have to stop here ;)
or still finished
but very good start

2019-01-28 12:55 UTC, dogi commented on _posts/2018-05-05-moodlemootph18.md
> +author: empeje
@empeje ? please make an different issue/PR for both name changes they can be in one but not here ;)

2019-01-28 12:55 UTC, dogi commented on _posts/2019-01-27-try-treehouses-remote.md
> +* RaspberryPi 3B or higher (any version with bluetooth)
tested on
- 3B
- zero W (and WH)
- 3B+
- 3A+

2019-01-28 12:55 UTC, dogi commented on _posts/2019-01-27-try-treehouses-remote.md
> +  - [ ] Install [treehouses/builder][GETTING_STARTED] image (in this example we use treehouses image version `75`)
- dev.ole.org or faster on cloudflare ... get our latest link here

2019-01-28 12:55 UTC, dogi commented on _posts/2019-01-27-try-treehouses-remote.md
> +  - [ ] Install Tor Browser (we have a fun demonstration)
:D

2019-01-28 12:55 UTC, dogi commented on _posts/2019-01-27-try-treehouses-remote.md
> +  - [ ] Install Tor Browser (we have a fun demonstration)
we should add link to torbrowser download

2019-01-28 16:12 UTC, empeje commented on _posts/2018-05-05-moodlemootph18.md
> +author: empeje
sure, done here https://github.com/treehouses/treehouses.github.io/pull/36

2019-01-28 17:09 UTC, empeje commented on _posts/2019-01-27-try-treehouses-remote.md
> +  - [ ] Install Tor Browser (we have a fun demonstration)
updated

2019-01-28 17:12 UTC, empeje commented on _posts/2019-01-27-try-treehouses-remote.md
> +  - [ ] Install [treehouses/builder][GETTING_STARTED] image (in this example we use treehouses image version `75`)
cloudfront you mean? what is the link @dogi?

2019-02-18 18:13 UTC, empeje commented on _posts/2019-01-27-try-treehouses-remote.md
> +* RaspberryPi 3B or higher (any version with bluetooth)
updated, please check @dogi

2020-11-15 04:59 UTC, closed without merging

2020-11-15 05:00 UTC, empeje commented
Hi @dogi I close this PR as I think things has changed in the Treehouses wiki.